imports:
- path: resources/service-account.jinja
  name: service-account.jinja
- path: resources/acknowledge.jinja
  name: acknowledge.jinja

resources:
- name: streamsec-sa
  type: service-account.jinja
- name: streamsec-init-ack
  type: acknowledge.jinja
  properties:
    serviceAccountEmail: $(ref.streamsec-sa.service-account-email)
    serviceAccountKey: $(ref.streamsec-sa.service-account-key)