imports:
- path: resources/init.jinja
  name: init.jinja

resources:
- name: streamsec-init
  type: init.jinja
  properties:
    region: us-central1
    apiUrl: {{ API_URL }}
    apiToken: {{ API_TOKEN }}