name: Zip and Upload to GCP

on:
  release:
    types: [ published ]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_PRODUCTION }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Zip the folder
        run: |
          (cd ./code/acknowledge && zip -r ../../gcp-init-ack.zip .)
          (cd ./code/events && zip -r ../../gcp-events-collection.zip . -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip")
          (cd ./code/flowlogs && zip -r ../../gcp-flow-logs-collection.zip . -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip")

      - name: Upload to GCP Bucket
        run: |
          gsutil cp gcp-init-ack.zip gs://streamsec-production-public-artifacts
          gsutil cp gcp-events-collection.zip gs://streamsec-production-public-artifacts
          gsutil cp gcp-flow-logs-collection.zip gs://streamsec-production-public-artifacts
