name: Zip and Upload to GCP

on:
  push:
    branches:
      - master # Change this if you want the action to run on different branches or triggers

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_STAGING }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Zip the folder
        run: |
          zip -r gcp-init-ack.zip ./code/acknowledge
          zip -r gcp-events-collection.zip ./code/events -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip"
          zip -r gcp-flow-logs-collection.zip ./code/flowlogs -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip"

      - name: Upload to GCP Bucket
        run: |
          gsutil cp gcp-init-ack.zip gs://streamsec-public-artifacts
          gsutil cp gcp-events-collection.zip gs://streamsec-public-artifacts
          gsutil cp gcp-flow-logs-collection.zip gs://streamsec-public-artifacts
