name: Zip and Upload to GCP

on:
  push:
    branches:
      - master # Change this if you want the action to run on different branches or triggers

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_STAGING }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Zip the folder
        run: |
          (cd ./code/acknowledge && zip -r ../../gcp-init-ack.zip .)
          (cd ./code/events && zip -r ../../gcp-events-collection.zip . -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip")
          (cd ./code/flowlogs && zip -r ../../gcp-flow-logs-collection.zip . -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip")
          (cd ./code/gke-logs && zip -r ../../gcp-gke-logs-collection.zip . -x "local/*" "mocks/*" "config/local.js" "*.yaml" "*.zip")
          (cd ./code/automated-integration && zip -r ../../gcp-automated-integration.zip .)

      - name: Upload to GCP Bucket
        run: |
          gsutil cp gcp-init-ack.zip gs://streamsec-public-artifacts
          gsutil cp gcp-events-collection.zip gs://streamsec-public-artifacts
          gsutil cp gcp-flow-logs-collection.zip gs://streamsec-public-artifacts
          gsutil cp gcp-gke-logs-collection.zip gs://streamsec-public-artifacts
          gsutil cp gcp-automated-integration.zip gs://streamsec-public-artifacts
